# config/secrets.yml

# Keep the production section only in production
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_token: <%= ENV["SECRET_TOKEN"] %>
  some_api_key: <%= ENV["SOME_API_KEY"] %>
  db_password: <%= ENV["DB_PASSWORD"] %>

# Keep the development and test sections only in development and test
development:
  secret_key_base: development_secret_key_base
  secret_token: development_secret_token
  some_api_key: development_api_key
  db_password: development_db_password

test:
  secret_key_base: test_secret_key_base
  secret_token: test_secret_token
  some_api_key: test_api_key
  db_password: test_db_password
