# config/secrets.yml

# Keep the production section only in production
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_token: <%= ENV["SECRET_TOKEN"] %>

# Keep the development and test sections only in development and test
development:
  secret_key_base: development_secret_key_base
  secret_token: development_secret_token

test:
  secret_key_base: test_secret_key_base
  secret_token: test_secret_token
